import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx convex dev` — not ours to lint.
    "convex/_generated/**",
    // `vercel build` output, and the env it pulls. Compiled bundles, so
    // linting them reports thousands of problems about code nobody wrote.
    ".vercel/**",
  ]),
]);

export default eslintConfig;
